spring.application.name=research-Assistant
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=
gemini.api.key=AIzaSyAuX-NofmNAutuR5t-RGOwg_H6I3Mm-UI8